# fly.toml app configuration file generated for backend-blue-cherry-7764 on 2025-05-06T09:36:55+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-blue-cherry-7764'
primary_region = 'syd'

[build]
  dockerfile = "app/backend/Dockerfile"
  context = "."  # root of the repo, to give access to shared/ and tsconfig.base.json

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
