name: Update Henyo Backend Image and Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'app/backend/**'
      - 'shared/**'
      - '.github/workflows/update-henyo-backend-image.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Log in to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

    - name: Build and push Docker image
      run: |
        docker build -t my-app:latest .
        docker tag my-app:latest ${{ secrets.ECR_URI }}/my-app:latest
        docker push ${{ secrets.ECR_URI }}/my-app:latest

    - name: SSH into EC2 and update container
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.ECR_URI }}/henyo-backend:latest
          docker stop henyo-backend || true
          docker rm henyo-backend || true
          docker run -d --name henyo-backend -p 3001:3001 ${{ secrets.ECR_URI }}/henyo-backend:latest

